### PR TITLE
dummy index file with meta redirection is added

### PR DESCRIPTION
**Pull request by luckywilliams**

### CODE REVIEW

**Comment by sarahscheffler** [comment]
Could you re-PR this to the (newly created) gh-pages branch please?  👍

**Comment by luckywilliams** [comment]
ok what should I name that branch ?

**Comment by sarahscheffler** [comment]
You don't have to change the name of your local branch, just the branch within this repo you're pushing to.  This command should work:
`git push origin master:gh-pages` (where `origin` is whatever you named this remote; see [here](https://help.github.com/articles/pushing-to-a-remote/#renaming-branches).)  That should push from your local master branch to this repository's gh-pages branch.

**Comment by luckywilliams** [comment]
Hi I have added a branch gh-pages as you let me know If I have did it right, thanks for your guidance on here.

Please check another pull request on gh-pages branch I have sent and let me know what we can do about this pull request ?

**Comment by sarahscheffler** [comment]
Closing this PR because we merged in #25 instead.

**Comment by luckywilliams** [comment]
ok thanks for help I am happy do to contribute :)

**Pull request closed without merging**
